### PR TITLE
Issue #108: 'Getting Started' and 'About this Project' pages

### LINKED ISSUE #97: Add checklist for what types of forms are supported for visibility
Users should be able to see what is supported so they don't fill out the forms and then end up running into something that they need that is missing

### LINKED ISSUE #108: Landing page
It would be really helpful to have a landing page with blurbs about what this project does right now and what it doesn't do. Perhaps a feature-to-feature comparison table with other popular tax products and their different tiers.

Side note, there are many people that would love to bury other popular tax products so if you're serious about this then you might consider doing a gofundme or some kind of crowd funding to give you more time to work on it.

### PR DESCRIPTION
**Pull request by eoncarlyle**
Fixes #97 and fixes #108. Created 'Getting Started' and 'About This Project' React elements underneath a new 'UsTaxes.org' section item. Copy for 'Getting Started' describes supported income forms, 1040 attachments, credits, and states of residency while 'About This Project' provides a short summary about the maintainers and information for prospective contributors. Created 'DirectButtons' react element in the `pager` module for a hyperlink box that conforms with the existing style, is used to link to '/info' route. 

Just as was the case for my last pull request, I'm not completely sure that  I'm following best practices. If editing the copy (as opposed to the code) of the two new pages would be better served by Google Doc editing comments rather than a lot of back-and-forth GitHub pull request comments, just let me know.

### CODE REVIEW

**Comment by eoncarlyle** [comment]
Does this also address Issue #97?

**Comment by zakpatterson** [comment]
> Does this also address Issue #97?

Yes if you just add "Fixes #108", "Fixes #97" to your PR body text, then those issues will be auto-closed when this is merged.

**Comment by zakpatterson** [comment]
Do we like the Getting Started to be included in the left side drawer and be part of the data entry flow? Or should the `/` route point to a full width page including desktop binary download links, with a prominent next step action to get the user started?

**Comment by thegrims** [comment]
>  The / route point to a full width page including desktop binary download links, with a prominent next step action to get the user started?

I like this option, maybe with the about us page content also integrated into the landing page lower down in the copy

**Comment by eoncarlyle** [comment]
This shouldn't have taken me as long as it did, but the latest commit addresses feedback from @thegrims and @zakpatterson

**Comment by thegrims** [comment]
@eoncarlyle looks good!

**Review by thegrims — APPROVED** [review]

**Review by zakpatterson — APPROVED** [review]

**Pull request merged**
