### PR TITLE
Dependabot updates

### PR DESCRIPTION
**Pull request by zakpatterson**
Need to check desktop build

### CODE REVIEW

**Comment by zakpatterson** [comment]
Tried out desktop build, works normally.

**Comment by thegrims** [comment]
The drop shadow for the form looks like it's getting cut off in the preview environment

**Comment by zakpatterson** [comment]
> The drop shadow for the form looks like it's getting cut off in the preview environment

Weird but what in the diff could possibly cause that

**Comment by zakpatterson** [comment]
It's being caused by this padding on the <main /> element, which comes from the `createMuiTheme`, conflicting with the box-shadow from our App.css file

So I think we need to bring the App.css stuff into the material-ui theme somehow.

image

**Comment by thegrims** [comment]
I wonder if the padding changed for main, because the same issue is not showing up on the live site

**Comment by thegrims** [comment]
alternatively, we could nix / modify the drop shadow

**Review by thegrims — APPROVED** [review]

**Comment by thegrims** [comment]
LGTM

**Pull request merged**
