### PR TITLE
Fix error handling of unset filing status

### LINKED ISSUE #1018: Navigating to Review and Print page without filing status breaks app
App goes blank if user has not picked a filing status and navigates to review page.

### PR DESCRIPTION
**Pull request by zakpatterson**
**What kind of change does this PR introduce?** (delete not applicable)
- Bugfix

Fixes #1018

### CODE REVIEW

**Comment by thegrims** [comment]
image
Interesting, I'm not seeing that error with filing status on the live site

**Comment by zakpatterson** [comment]
> Interesting, I'm not seeing that error with filing status on the live site

You need to have a 1099-B with gains to get the error.

**Comment by thegrims** [comment]
> > Interesting, I'm not seeing that error with filing status on the live site
> 
> You need to have a 1099-B with gains to get the error.

Got it

**Review by thegrims — APPROVED** [review]
LGTM

**Pull request merged**
