### PR TITLE
Add refund credit for excess SS tax withholding from W2s

### PR DESCRIPTION
**Pull request by aymarino**
Fills logic in Schedule 3 to determine if there was too much payroll withholding for SS tax, which counts as a refundable credit on form 1040 line 3, and attaches schedule 3 to the return if so.

SS tax is a flat payroll tax, but only up to a certain threshold. The typical case is someone who has multiple jobs with income totaling more than that threshold, each individual job will withhold up to the max SS tax (with IFAIK no way to adjust it during the year), so the amount withheld in excess of that individual maximum is refundable.

### CODE REVIEW

**Comment by zakpatterson** [comment]
@aymarino I reviewed this a bit and made a few simple changes. I didn't actually mean to push this directly into your PR, oops! Anyway this looks great.

**Comment by zakpatterson** [comment]
Sorry, I committed a few things here and deleted them.

**Comment by zakpatterson** [comment]
@aymarino, This is awesome, thanks so much. I made a few minor changes and sent them to you here: https://github.com/aymarino/UsTaxes/pull/1

If you have time again, take a look and merge if those changes make sense. No problem if you don't get another bit of time soon, I'll merge them myself in a day or two.

**Comment by aymarino** [comment]
Thanks for the review, the changes make sense--the SS limit changes constantly so good idea to keep it centralized with other constants. I left one comment for a typo that was introduced and you probably want to fix. If you fix over there I'll merge it in, or you can just merge it all on this PR

**Comment by zakpatterson** [comment]
Great, just merged that in. I'll give @thegrims a shot at reviewing and let him merge.

**Review by thegrims — APPROVED** [review]

**Pull request merged**
