### PR TITLE
Upgrade react router to v6

### LINKED ISSUE #789: Migrate react-router to v6
react-router has gone through a major update.

Our dependency issues:
* react-router-last-location 
  * [Users have been begging maintainers](https://github.com/hinok/react-router-last-location/issues/65) for new version for several months. we could fork this repo and release updates, or just insource the functionality.
 * This dependency is also blocking us from upgrading to React 17.
 * `react-router`v6 [doesn't yet support `<Prompt>`](https://github.com/remix-run/react-router/blob/5730e28a7472e3a1b967d95c5c4cc643c570d5c7/docs/upgrading/v5.md#prompt-is-not-currently-supported)

### PR DESCRIPTION
**Pull request by zakpatterson**
This updates React Router to v6.

From React-router:
 * Prompt no longer included, see [this issue](https://github.com/remix-run/react-router/issues/8139) - this means for now we lose the "Are you sure you want to leave this page and lose data" feature for now.
 * Note that Prompt's current master functionality is currently broken in the desktop version. It shows the prompt after navigating the page.
 
closes #964 - React-router upgrade
closes #963 - React-router-dom upgrade
Fixes #789 - react-router

### CODE REVIEW

**Comment by thegrims** [comment]
What are the advantages of react router v6 vs v5?

**Comment by zakpatterson** [comment]
Not sure, honestly I hadn't considered an alternative to keeping up to date with dependency releases. Is there one

**Comment by thegrims** [comment]
I was thinking along the lines of holding off on an update to the latest version until either prompt is implemented or support is dropped for v5

**Comment by zakpatterson** [comment]
That's fine, the prompt feature is currently broken on desktop, I'll try to figure out why, fine with keeping this branch alive for a while.

**Comment by thegrims** [comment]
@zakpatterson I think maybe we should just merge it to keep your work from drifting too far out of date with master, thoughts?

**Review by thegrims — APPROVED** [review]

**Pull request merged**
