### PR TITLE
Estimated tax payments

### PR DESCRIPTION
**Pull request by ctSkennerton**
Here is my initial pass at having a page for payments and implementing estimated taxes for form 1040 line 26.

### CODE REVIEW

**Comment by zakpatterson** [comment]
Hey I saw this oddly was passing the linter action but failing when trying to deploy, due to two linter warnings. So I fixed the `npm run lint` command to disallow all warnings and cleaned those two up.

**Comment by zakpatterson** [comment]
I'm going to start gently nudging people to set up signed commits. I think it's a good step to take for code security:

https://github.com/ustaxes/UsTaxes/issues/465

No problem on this PR, but at some point in the near future we'll start requiring it.

**Comment by ctSkennerton** [comment]
Thank you @zakpatterson! I added in a gig key so my future commits should be properly verified.

**Comment by thegrims** [comment]
I think it might be good to start off estimated taxes with a question prompt of 

> did you already make payments towards your 2020 taxes this year or last year

or similar, to avoid confusion of what this field is asking for

**Comment by ctSkennerton** [comment]
I've updated the code to fix the issue with saving and also added in a label field in case a user has multiple payments and wants to provide a note for what each one is. I think the CI is running into the same issue as documented in #588, which is causing it to fail.

**Comment by zakpatterson** [comment]
> I've updated the code to fix the issue with saving and also added in a label field in case a user has multiple payments and wants to provide a note for what each one is. I think the CI is running into the same issue as documented in #588, which is causing it to fail.

Agree. Reran twice and it passed.

**Review by thegrims — APPROVED** [review]

**Comment by zakpatterson** [comment]
Looks good, not going to hold this up for testing given #588.

**Pull request merged**
