### PR TITLE
Support multiple years

### LINKED ISSUE #753: W2 Medicare wages allowed to be greater than actual wages
It's possible to have wages be zero, add medicare wages above the threshold, and have taxes due with no income.

### PR DESCRIPTION
**Pull request by zakpatterson**
Add form implementations for 2021
Work on 2019 form implementations is going on here: https://github.com/zakpatterson/UsTaxes/pull/91

**What kind of change does this PR introduce?**
- Feature
- Docs
- Code style update
- Refactor
- Build-related changes

After a lot of experimentation in #662, I suggest we maintain a monorepo structure.

I believe the benefits of splitting the repository will never outweigh the costs. The initial motivations of splitting the repo involved being able to release the forms implementations to NPM for potential use in other projects, and maintaining one coherent view of the forms implementations, using git to jump between years. 

The first sign this was a bad idea was the need for `core` project that the forms branches and the main repo could access. Splitting the code on tax year using git submodules means that now there's 2N+2 git modules that can potentially get out of sync, as each year requires a copy of `core`, and the main project requires a copy of `core`. This can be mitigated with scripts, but we're not getting anything for that complexity.

We will still be able to release from a single directory in our source tree down the line, so I think even with a monorepo structure we can release our form implementations. Splitting is not necessary.

While having separate branches of our forms implementation would solve the second goal, it comes at considerable cost as each year's branch will continue to diverge from each other. To mitigate this we will require PRs to bring them closer together, [example](https://github.com/ustaxes/ustaxes-forms/pull/9). Alternatively, in a single repository, we can simply diff the year directories to see how they are drifting, and adjust accordingly, which should be less cumbersome.

Anyway, the experiment on #662 was valuable and the form implementations developed there were easily copied into this project. At this point, however, I propose we just reorganize the source tree and leave a single repository.

Closes #662 
Fixes #753

### CODE REVIEW

**Comment by thegrims** [comment]
image


filing status is invalidated when year is switched back to year with save state, resets after page refresh 


image

**Comment by thegrims** [comment]
Getting this error when trying to print federal 1040 forms 
image

**Comment by thegrims** [comment]
recording

when the state is Illinois, an error is thrown when navigating to /createpdf

<details><summary>Browser metadata</summary>





```
Path:      /createpdf
Browser:   Chrome 96.0.4664.110 on Windows 10
Viewport:  1536 x 754 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-778--ustaxes.netlify.app%2Fcreatepdf&os=Windows&os_version=10&browser=Chrome&browser_version=96.0&resolution=1536x754&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-778--ustaxes.netlify.app/createpdf) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61c0f53b5f405300078fa929&commentID=61c2d430550c2327582a6968&resolution=resolved)

**Comment by thegrims** [comment]
image

**Review by thegrims — CHANGES_REQUESTED** [review]
See above comments

**Comment by thegrims** [comment]
When year is switched to 2021, data from 2020 is filled into the form elements

recording


<details><summary>Browser metadata</summary>





```
Path:      /income/w2jobinfo
Browser:   Chrome 96.0.4664.110 on Windows 10
Viewport:  1536 x 754 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-778--ustaxes.netlify.app%2Fincome%2Fw2jobinfo&os=Windows&os_version=10&browser=Chrome&browser_version=96.0&resolution=1536x754&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-778--ustaxes.netlify.app/income/w2jobinfo) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61c7c59b1ff6740007643993&commentID=61c7ffedf3060ded6d28cabb&resolution=resolved)

**Comment by thegrims** [comment]
Looks like it only happens when the migration function is used

**Review by thegrims — APPROVED** [review]

**Comment by thegrims** [comment]
Texas and other states that don't have income tax filing shouldn't have warnings showing that there aren't state income tax forms available

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /createpdf
Browser:   Chrome 96.0.4664.110 on Windows 10
Viewport:  1536 x 754 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-778--ustaxes.netlify.app%2Fcreatepdf&os=Windows&os_version=10&browser=Chrome&browser_version=96.0&resolution=1536x754&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-778--ustaxes.netlify.app/createpdf) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61c7c59b1ff6740007643993&commentID=61c807d09516343bcbace6a5&resolution=resolved)

**Comment by thegrims** [comment]
Income of $10,000 should qualify for $2,954 of EIC credit, not 0

recording


<details><summary>Browser metadata</summary>





```
Path:      /createpdf
Browser:   Chrome 96.0.4664.110 on Windows 10
Viewport:  1536 x 754 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-778--ustaxes.netlify.app%2Fcreatepdf&os=Windows&os_version=10&browser=Chrome&browser_version=96.0&resolution=1536x754&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-778--ustaxes.netlify.app/createpdf) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61c7c59b1ff6740007643993&commentID=61c808c1f3060dfe1d28c5cd&resolution=resolved)

**Comment by thegrims** [comment]
On the IL-1040-V, not sure about the starting exemption about in a, but none of the checkboxes in b aren't checked so $2,000 shouldn't be added
image

We may need to address this separately though

**Comment by zakpatterson** [comment]
Yes, the EIC and IL 1040V seem like current issues in production. Seems like we're not handling refundable credits correctly.

I'll handle the state warnings and merge, then solve the other two things separately.

**Comment by thegrims** [comment]
> Yes, the EIC and IL 1040V seem like current issues in production. Seems like we're not handling refundable credits correctly.
> 
> I'll handle the state warnings and merge, then solve the other two things separately.

I don't think the same EIC issue is showing up in prod
image

**Comment by zakpatterson** [comment]
I think I got the display of the proper EIC credit, as well as a more helpful message about no filing states.

image

**Comment by zakpatterson** [comment]
Fixed up the IL1040 line 10b issue here for efficiency.

**Comment by thegrims** [comment]
Error thrown when navigating to the /createpdf page and no information is inputted previously

recording


<details><summary>Browser metadata</summary>





```
Path:      /createpdf
Browser:   Chrome 96.0.4664.110 on Windows 10
Viewport:  1536 x 754 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-778--ustaxes.netlify.app%2Fcreatepdf&os=Windows&os_version=10&browser=Chrome&browser_version=96.0&resolution=1536x754&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-778--ustaxes.netlify.app/createpdf) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61ccc681cd0d5800075450b8&commentID=61ccde286b8065ad25d74b83&resolution=resolved)

**Comment by thegrims** [comment]
image
Error message

**Comment by thegrims** [comment]
Should ask if fincen is required if you have a financial interest in an asset located in a foreign country

image

**Comment by thegrims** [comment]
Saved 1099-R information is incorrectly pulled into new 1099 form input

recording


<details><summary>Browser metadata</summary>





```
Path:      /income/f1099s
Browser:   Chrome 96.0.4664.110 on Windows 10
Viewport:  1536 x 754 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-778--ustaxes.netlify.app%2Fincome%2Ff1099s&os=Windows&os_version=10&browser=Chrome&browser_version=96.0&resolution=1536x754&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-778--ustaxes.netlify.app/income/f1099s) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61cd3f4e44e8860007f9f33c&commentID=61cd6c942738da8b5f6fe0ad&resolution=resolved)

**Comment by thegrims** [comment]
image
Additional child tax credit on line 15 on form 8812 should be $1125 instead of empty

**Comment by thegrims** [comment]
this problem appears to be in prod as well

**Comment by zakpatterson** [comment]
As much as this PR has turned into a rewrite of the code, I think it's time to consider merging it so we can deal with other issues without conflicts. Let me know what you think. I'm open to cleaning it up in some way if it would help.

**Comment by thegrims** [comment]
> As much as this PR has turned into a rewrite of the code, I think it's time to consider merging it so we can deal with other issues without conflicts. Let me know what you think. I'm open to cleaning it up in some way if it would help.

That makes sense

**Review by thegrims — APPROVED** [review]

**Comment by zakpatterson** [comment]
Really good QA / review work, lets gooooo 2021...

**Pull request merged**
