### PR TITLE
Added html favicon, title, and meta description

### PR DESCRIPTION
**Pull request by vermaarn**
(Just a small pr) The tab/website name and meta information are still from the default Create React App setup, so I updated some meta-information to reflect the project. I titled the website "US Taxes" and set the description to "A website to help file taxes in the United States."

I also add a simple favicon and a 516x516 / 192x192 version of said icon. Here is a sample below:
logo192

I simple generated it from this site: https://favicon.io/favicon-generator/ with the following information:
- Font Title: Gelasio
- Font Author: Copyright 2019 The Gelasio Project Authors (https://github.com/SorkinType/Gelasio)
- Font Source: http://fonts.gstatic.com/s/gelasio/v3/cIf9MaFfvUQxTTqSxCmrYGkHgIs.ttf
- Font License: SIL Open Font License, 1.1 (http://scripts.sil.org/OFL)
- Background color: #0088ff ; rgba(0,136,255,255)

### CODE REVIEW

**Comment by zakpatterson** [comment]
Thanks so much @vermaarn for this and your interest!  Our main theme color is currently defined here: https://github.com/ustaxes/UsTaxes/blob/master/src/components/Main.tsx#L29

Would you update the favicon to that? And the entire site is using a sans-serif font, so I think the favicon would use that too. 

On the description, this project builds a website as well as a desktop application. So instead of “A website...” I think it could just be “An application...”

Thanks so much for the PR!!

**Comment by vermaarn** [comment]
No problem! 
Here an update on the font and color for the icon, (I choose Roboto which is part of the sans-serif font-family):
- Font Title: Roboto
- Font Author: Copyright 2011 Google Inc. All Rights Reserved.
- Font Source: http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf
- Font License: Apache License, version 2.0 (http://www.apache.org/licenses/LICENSE-2.0.html)
- Background color: #00e676
- Text color: #000000
Here is a picture below
logo192

**Comment by zakpatterson** [comment]
@vermaarn thanks for those updates! I like it. @thegrims merge if agree?

**Comment by thegrims** [comment]
Looks great!

**Pull request merged**
