### PR TITLE
Move form inclusion logic

### PR DESCRIPTION
**Pull request by zakpatterson**
Makes `isNeeded` and `copies` part of each form's interface

Instead of using form === undefined as a test for including an attachment, allow the form to be generated but not be attached. This will be helpful if we want to display a given form to a user even though the form ends up not being needed

For example we could display the Schedule A in order to show the user that their itemized deductions ended up being less than standard.

**What kind of change does this PR introduce?**
- Refactor

### CODE REVIEW

**Comment by thegrims** [comment]
Navigating to the review and print page with this info 

```
{
  "assets": [],
  "Y2019": {
    "f1099s": [],
    "w2s": [],
    "estimatedTaxes": [],
    "realEstate": [],
    "taxPayer": {
      "dependents": []
    },
    "questions": {},
    "f1098es": [],
    "f3921s": [],
    "scheduleK1Form1065s": [],
    "stateResidencies": [],
    "healthSavingsAccounts": [],
    "credits": [],
    "individualRetirementArrangements": []
  },
  "Y2020": {
    "f1099s": [],
    "w2s": [],
    "estimatedTaxes": [],
    "realEstate": [],
    "taxPayer": {
      "dependents": []
    },
    "questions": {},
    "f1098es": [],
    "f3921s": [],
    "scheduleK1Form1065s": [],
    "stateResidencies": [],
    "healthSavingsAccounts": [],
    "credits": [],
    "individualRetirementArrangements": []
  },
  "Y2021": {
    "f1099s": [],
    "w2s": [
      {
        "employer": {
          "EIN": "999999999",
          "employerName": "anonymous employer"
        },
        "occupation": "occupation",
        "income": 24000,
        "medicareIncome": 47,
        "fedWithholding": 629,
        "ssWages": 200,
        "ssWithholding": 200,
        "medicareWithholding": 200,
        "stateWages": 200,
        "stateWithholding": 328,
        "box12": {},
        "state": "KS",
        "personRole": "PRIMARY"
      }
    ],
    "estimatedTaxes": [],
    "realEstate": [],
    "taxPayer": {
      "dependents": [],
      "filingStatus": "S",
      "primaryPerson": {
        "address": {
          "address": "Eaque exercitationem",
          "city": "Blanditiis Nam est a",
          "aptNo": "Nobis aute libero ut",
          "state": "IN",
          "zip": "804920000"
        },
        "firstName": "PRIMARYfirst",
        "lastName": "PRIMARYlast",
        "ssid": "100000000",
        "isTaxpayerDependent": false,
        "role": "PRIMARY"
      },
      "contactPhoneNumber": "1234567890",
      "contactEmail": "a@b.com"
    },
    "questions": {},
    "f1098es": [],
    "f3921s": [],
    "scheduleK1Form1065s": [],
    "stateResidencies": [
      {
        "state": "ND"
      }
    ],
    "healthSavingsAccounts": [],
    "credits": [],
    "individualRetirementArrangements": []
  },
  "activeYear": "Y2021",
  "_persist": {
    "version": -1,
    "rehydrated": true
  }
}
```
results in the error
`Cannot read properties of undefined (reading 'credit')`

**Comment by thegrims** [comment]
If filing status is set to single, and the application is navigated to /createpdf,
`Uncaught Error: Invalid information` is thrown

**Review by thegrims — CHANGES_REQUESTED** [review]
errors generated by /createdpdf page

**Review by thegrims — CHANGES_REQUESTED** [review]
> If filing status is set to single, and the application is navigated to /createpdf,
Uncaught Error: Invalid information is thrown

Still seeing this error showing up in the preview environment

**Comment by zakpatterson** [comment]
> Still seeing this error showing up in the preview environment

Good catch, sorry for delay: 

image

**Review by thegrims — APPROVED** [review]
LGTM! Thanks for your contribution

**Pull request merged**
