### PR TITLE
Y2022

### PR DESCRIPTION
**Pull request by ctSkennerton**
This is a start for adding in 2022. There are a number of form changes from 2021, which are not implemented yet but perhaps it can be added to over time.

**What kind of change does this PR introduce?** 
- Feature

### Check and update forms
Go through each of the following forms and determine if:
- any of the fields have changed from last year, including the addition or removal of fields.
- The calculations of the fields are the same from 2021
- And constants, like income limits, have changed from 2021

- [x] 1040
- [x] schedule 1
- [x] schedule 2
- [x] schedule 3
- [x] schedule 8
- [x] schedule A
- [x] schedule B
- [x] schedule D
- [x] schedule E
- [ ] schedule EIC
- [x] schedule SE
- [x] 2555
- [x] 4563
- [x] 6251
- [x] 8889
- [x] 8949
- [x] 8959
- [x] 8960
- [x] 8995
- [x] 8995A

### CODE REVIEW

**Comment by willkrakow** [comment]
Do you have a list of remaining forms / features that need to be updated for Y2022? Happy to help out

**Comment by ctSkennerton** [comment]
Essentially all of them need to be checked and updated. I’ve looked at 1040 so far and put in some placeholders for fields that need to be updated. So take your pick of the other forms and reply in the thread for which one you’re working on so work doesn’t get duplicated.On Feb 19, 2023, at 15:35, willkrakow ***@***.***> wrote:﻿
Do you have a list of remaining forms / features that need to be updated for Y2022? Happy to help out

**Comment by ctSkennerton** [comment]
I checked and updated 8995 and 8995A for 2022

**Review by thegrims — CHANGES_REQUESTED** [review]
The default year should be changed to 2022, we can also fix that in a follow up pull request if needed though

**Comment by thegrims** [comment]
Just finished trying it on my own taxes, and it looks good, unit tests just need to be updated now

**Review by thegrims — APPROVED** [review]
LGTM! Thanks for putting this together

**Pull request merged**
