### PR TITLE
Expanded1099 r

### PR DESCRIPTION
**Pull request by ctSkennerton**
- New logic added in to separate 1099-R coming from 401K vs IRA which need to be reported differently
- Input now takes into account the gross distribution, taxable amount, and income tax withheld

### CODE REVIEW

**Comment by zakpatterson** [comment]
Awesome. There was a question about how this income affects the EIC eligibility. Have you checked on that while doing this amazing work?

**Comment by ctSkennerton** [comment]
Sorry, I haven't looked at EIC.

**Comment by ctSkennerton** [comment]
Though based on [this document](https://www.irs.gov/credits-deductions/individuals/earned-income-tax-credit/earned-income-and-earned-income-tax-credit-eitc-tables) it seems like it does not count as earned income

> Earned income does not include:

>Pay you got for work when you were an inmate in a penal institution
>Interest and dividends
>Pensions or annuities
>Social Security
>Unemployment benefits
>Alimony
>Child support

**Comment by zakpatterson** [comment]
Ah thanks, I think that helps clarify. So if the 1099R is the persons only income then they would not be eligible, but if they had other earned income that qualified them, the 1099r would add to their AGI and reduce their credit.

**Comment by zakpatterson** [comment]
It's behaving as expected with respect to EIC.

**Review by zakpatterson — APPROVED** [review]

**Comment by thegrims** [comment]
@ctSkennerton Do the readme/start pages 1099-R description need to be updated to reflect these changes?

**Comment by zakpatterson** [comment]
nice catch @thegrims, current README just references IRA accounts so additional doc descriptions there and the start page would  be nice.

**Comment by ctSkennerton** [comment]
thanks for pointing it out. I've updated the readme and getting started guides

**Comment by zakpatterson** [comment]
Looks good.

**Review by thegrims — APPROVED** [review]

**Pull request merged**
