### PR TITLE
Enhance "other investments" csv transaction importer

### PR DESCRIPTION
**Pull request by zakpatterson**
**What kind of change does this PR introduce?** (delete not applicable)
- Feature
 
Add a filter and summary table for assets parsed from a csv file.
Refactors `FormListContainer` so that just the open/close functionality is available.
Use react-data-table to display assets list

image

Addresses #933

### CODE REVIEW

**Comment by thegrims** [comment]
image
Can the assets view be changed to follow the materialui theme light / dark mode?

**Comment by thegrims** [comment]
Not seeing the build portfolio button with all columns selected
image

**Comment by zakpatterson** [comment]
Think I got those, the DataTable component comes with its own "createTheme", so I was able to simplify the styles a lot using that.

**Comment by thegrims** [comment]
image
can some padding be added between these elements?

**Comment by thegrims** [comment]
image
I think this "security" field should be something like "find sales for stock" or something to be clear on what it is used for, and to make it clear it's for filtering

**Comment by thegrims** [comment]
image
Minor nitpick, can the assets box be made the same width as the summary of sales box?

**Review by thegrims — APPROVED** [review]

**Pull request merged**
