### PR TITLE
Fix #521 Add dark theme support via system settings

### LINKED ISSUE #521: Missing vertical padding / margin on 1099 SSA form labeledInputs
image

### PR DESCRIPTION
**Pull request by bluSCALE4**
Add dark theme support via system settings. Buttons could use some love, let me know if we want to address them in this PR.

theme

### CODE REVIEW

**Comment by thegrims** [comment]
I think the dark grey buttons should be whitesmoke/grey or similar in dark mode for more contrast

**Comment by bluSCALE4** [comment]
> Minor nitpick, but I think it would be best if the close buttons in subforms remained red
Can we focus on that in another PR? I plan on taking a deeper dive into colors.

**Review by thegrims — APPROVED** [review]

**Comment by thegrims** [comment]
image
section titles overlay menu elements on scroll down

**Comment by bluSCALE4** [comment]
> section titles overlay menu elements on scroll down

This is actually a feature. If we give the section heading a background, it'll overlay the pages. I was playing around with added a dynamic shadow and it looks ok. I think making them sticky looks a bit busy.

**Comment by bluSCALE4** [comment]
swipe

**Review by thegrims — CHANGES_REQUESTED** [review]
image

'Previous' and 'add' buttons should be dark in light mode

**Review by thegrims — APPROVED** [review]

**Pull request merged**
