### PR TITLE
Add transaction csv importer for uncovered 8949 transactions

### PR DESCRIPTION
**Pull request by zakpatterson**
**What kind of change does this PR introduce?** (delete not applicable)
- Feature

Given a list of transactions, build a portfolio of lots, applying FIFO rules to each portfolio position.

This could apply to anything that requires form 8949 to be filed. These days it's vital for anyone with crypto transactions, as those people will receive 1099-K for withdrawals, but no 1099-B showing gains and losses. They're required to track their positions individually and match transactions in FIFO order.

Later I suppose another need for this could be to reconcile wash sales between multiple brokerage accounts. 

## Example usage
Import a file of transactions, and build portfolio positions applying sales to purchases in FIFO order:

https://user-images.githubusercontent.com/1987109/154786602-bef4cf39-8001-41bc-b746-bf741bd29779.mp4

Import a file of transactions containing a sale for which there are no securities to sell (this is an error, missing portfolio data).

https://user-images.githubusercontent.com/1987109/154786605-c0a4cfd5-90d4-4eea-930d-f148258c59c7.mp4

### CODE REVIEW

**Comment by thegrims** [comment]
screenshot

looks like the placement of the load csv button is off

<details><summary>Browser metadata</summary>





```
Path:      /income/otherinvestments
Browser:   Chrome 98.0.4758.82 on Windows 10
Viewport:  1536 x 754 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-933--ustaxes.netlify.app%2Fincome%2Fotherinvestments&os=Windows&os_version=10&browser=Chrome&browser_version=98.0&resolution=1536x754&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-933--ustaxes.netlify.app/income/otherinvestments) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=620db6ce28a9e400072445ff&commentID=620decbc8db7603f01e9f777&resolution=resolved)

**Comment by zakpatterson** [comment]
Sorry. I meant to mark this as a work in progress. Lot’s of uncommitted work and work left to be done here. Need probably another day.

**Comment by thegrims** [comment]
> Sorry. I meant to mark this as a work in progress. Lot’s of uncommitted work and work left to be done here. Need probably another day.

Ok, no worries!

**Comment by zakpatterson** [comment]
This is getting pretty close. I think I need to add a few test CSV files for review and ideally with unit tests on them.

**Comment by thegrims** [comment]
Looks like the column labels don't show up correctly in dark mode, table is still light mode colors
image

**Comment by thegrims** [comment]
Drop first N rows showing up as NaN
image

**Comment by zakpatterson** [comment]
Got the NaN and dark mode issue done, but I notice it is not handling errors well if, for example, there's a date that is not parsed correctly (encountered when I forgot to skip the header row of the CSV), so I'll handle that next.

**Comment by thegrims** [comment]
image
padding should be added between the import portfolio and reset buttons

**Comment by zakpatterson** [comment]
Think I got it, give it another try!

**Comment by thegrims** [comment]
image
if quantity is set to the trade id column of the test data, the build portfolio button doesn't appear even if all the other fields are selected

**Comment by zakpatterson** [comment]
> if quantity is set to the trade id column of the test data, the build portfolio button doesn't appear even if all the other fields are selected

Nice spotting, I didn't see this initially, but if i set a duplicate column and then fixed it back to quantity I saw it wasn't available. I think I got it now.

**Comment by thegrims** [comment]
recording

When importing trades, trades can be imported with empty fields that would fail the form validations


<details><summary>Browser metadata</summary>





```
Path:      /income/otherinvestments
Browser:   Chrome 98.0.4758.102 on Windows 10
Viewport:  1536 x 754 @1.25x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-933--ustaxes.netlify.app%2Fincome%2Fotherinvestments&os=Windows&os_version=10&browser=Chrome&browser_version=98.0&resolution=1536x754&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-933--ustaxes.netlify.app/income/otherinvestments) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=622052c9fdccad0007a6fb99&commentID=62205c8bf22b075c29164b3f&resolution=resolved)

**Comment by zakpatterson** [comment]
> When importing trades, trades can be imported with empty fields that would fail the form validations

Yes, that display of positions was implemented when we were thinking about a single real estate transaction, but the importer is also trying to support buys that have not been closed out yet. 

Do you think we should just replace that list display with the data table like in the preview?

I don't know about manually adding positions though, perhaps that should just be separate in the UI.

**Comment by thegrims** [comment]
> > When importing trades, trades can be imported with empty fields that would fail the form validations
> 
> Yes, that display of positions was implemented when we were thinking about a single real estate transaction, but the importer is also trying to support buys that have not been closed out yet.
> 
> Do you think we should just replace that list display with the data table like in the preview?
> 
> I don't know about manually adding positions though, perhaps that should just be separate in the UI.

Gotcha, that makes sense, I think it looks good for now!

**Review by thegrims — APPROVED** [review]

**Pull request merged**
