### PR TITLE
Added Schedule A

### PR DESCRIPTION
**Pull request by ssigwart**
**What kind of change does this PR introduce?**
- Feature

Adds schedule A

### CODE REVIEW

**Comment by zakpatterson** [comment]
This looks really good @ssigwart, I just added a couple things here, including a property based test for Schedule A.

Feel free to merge here if it makes sense, or if I don't hear from you I'll merge it here. Thanks for this awesome contribution!!

https://github.com/ssigwart/UsTaxes/pull/1

@thegrims I just reviewed code, if you would like to review UI please do.

**Comment by ssigwart** [comment]
Thanks, @zakpatterson.  It doesn't look like I have permission to merge.

Thanks for adding the tests and some cleanup.  I'm going to try to add some other forms, so I'll try to take those changes into account too.

**Comment by zakpatterson** [comment]
> It doesn't look like I have permission to merge.

If you press the merge button here: https://github.com/ssigwart/UsTaxes/pull/1 my commits will be incorporated to this PR.

**Comment by ssigwart** [comment]
Ah.  I see.  You were merging to my branch.  Thanks.  I merged it.

**Comment by thegrims** [comment]
Looks good! Maybe we can include a blurb about how the itemized deductions will only be used if they are calculated to give a higher deduction than the standard deduction

**Comment by thegrims** [comment]
for charitable gifts other than by cash or check, we should either remove or limit gift to under $500 because of the form instructions

>  If you made any gift of $250 or more,see instructions. You must attach Form 8283 if over $500

**Comment by ssigwart** [comment]
I added a note and limited "other than by cash or check" to $500.

**Review by thegrims — APPROVED** [review]
LGTM! Thanks for your contribution.

**Comment by zakpatterson** [comment]
@ssigwart Is it ok if I mention you on our Twitter? Can you follow the ustaxesorg there. Thanks!!

**Comment by ssigwart** [comment]
@thegrims and @zakpatterson, thanks for helping me get this merged and the great product.  I don't have a Twitter account.  Looks like there's an `ssigwart`, but that's not me.

**Comment by zakpatterson** [comment]
Ah no problem. I'll just mention your name then. Adding another primary schedule brings us a giant step closer to completeness, so it's a big deal for the project. Definitely join the discord too and let us know if there's another feature you would like to tackle.

**Pull request merged**
