### PR TITLE
Add ajv7 as separate dependency

### LINKED ISSUE #115: Fix documentation for running as desktop application, or wait for new tauri release
```
➜  ustaxes git:(master) yarn desktop
yarn run v1.22.10
$ node ./setup.js && tauri dev
[tauri]: running dev
NOT SUPPORTED: option format. `validateFormats: false` can be used instead.
NOT SUPPORTED: option nullable. "nullable" keyword is supported by default.
NOT SUPPORTED: option uniqueItems. "uniqueItems" keyword is always validated.
DEPRECATED: option unicode. "minLength"/"maxLength" account for unicode characters by default.
(node:21125) UnhandledPromiseRejectionWarning: Error: strict mode: unknown keyword: "defaultProperties"
    at Object.checkStrictMode (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/validate/index.js:183:15)
    at Object.checkUnknownRules (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/util.js:32:24)
    at checkKeywords (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/validate/index.js:118:12)
    at Object.validateFunctionCode (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/validate/index.js:14:9)
    at Ajv.compileSchema (/home/projects/oss/ustaxes/node_modules/ajv/dist/compile/index.js:78:20)
    at Ajv._compileSchemaEnv (/home/projects/oss/ustaxes/node_modules/ajv/dist/core.js:444:37)
    at Ajv.compile (/home/projects/oss/ustaxes/node_modules/ajv/dist/core.js:139:38)
    at Object../src/types/config.validator.ts (/home/projects/oss/ustaxes/node_modules/tauri/dist/api/dev.js:1665:37)
    at __webpack_require__ (/home/projects/oss/ustaxes/node_modules/tauri/dist/api/dev.js:1910:42)
    at Object../src/helpers/tauri-config.ts (/home/projects/oss/ustaxes/node_modules/tauri/dist/api/dev.js:446:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2.36s.
```

### PR DESCRIPTION
**Pull request by zakpatterson**
Tauri's build script expects ajv6 to be available at the root
level, so I have to downgrade the default ajv in package.json
and alias it to ajv7 for our project.

See https://github.com/tauri-apps/tauri/issues/1250

Fixes #115

We just have to remember to undo this when tauri releases.

Also I think our commits have been switching back and forth with `package-lock.json`. This commit is created using npm 7.6.0.  npm > 7 updates package-lock.json's version and format, so let's try to standardize on npm > 7 going forward?

### CODE REVIEW

**Comment by thegrims** [comment]
> Also I think our commits have been switching back and forth with package-lock.json. This commit is created using npm 7.6.0. npm > 7 updates package-lock.json's version and format, so let's try to standardize on npm > 7 going forward?

Yeah, I have noticed that as well. Sounds good!

**Comment by thegrims** [comment]
I'm having some issues trying to validate the tauri desktop build, keep getting 
```
thread 'main' panicked at 'failed to spawn command: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\grims\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-bundler-0.9.4\src\bundle\common.rs:282:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 app:spawn Command "cargo" failed with exit code: 101 +0ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

 app:tauri Shutting down tauri process... +1ms
```

for 
`npm run desktop-release`

I think it should be good to merge anyways though because the preview seems to be working correctly and most builds in the future will probably be using Linux rather than windows as their environment

**Review by thegrims — APPROVED** [review]

**Comment by zakpatterson** [comment]
Ok sounds fine. We should debug that issue though. I don’t know if the desktop releases for windows will have to be built on a windows machine.

**Comment by thegrims** [comment]
@zakpatterson I found this github action for building a tauri app binary and it looks like it builds windows, mac, and Linux binaries from the same OS https://github.com/tauri-apps/tauri-action#creating-a-release-and-uploading-the-tauri-bundles

**Comment by zakpatterson** [comment]
Ah yeah that’s awesome. I think automating builds and releases now to GitHub will be a perfect step. I also started on the landing page. Those two things together will be huge.

**Pull request merged**
