### PR TITLE
Try out tauri 1.0 beta

### PR DESCRIPTION
**Pull request by zakpatterson**
This gets it running using the recently published beta 1.0 release from tauri. Try it out!

### CODE REVIEW

**Comment by thegrims** [comment]
Getting 
image
When running in powershell on windows 10

**Comment by zakpatterson** [comment]
> Getting
> image
> When running in powershell on windows 10

Strange, the [tauri migration guide](https://tauri.studio/en/docs/usage/guides/migration/) is specific about removing `winres`

Maybe rm your /src-tauri/target directory?

**Comment by zakpatterson** [comment]
> Getting...
> When running in powershell on windows 10

Ok, found a few more differences in the default tauri bootstrap for windows, try again when you can!

**Comment by thegrims** [comment]
@zakpatterson Getting a slightly different error now but still in the same vein
image

**Comment by zakpatterson** [comment]
@thegrims ok, think I got it. we will figure out how this rust build works eventually.

**Comment by thegrims** [comment]
image
The build succeeds now but results in an empty window when the application is run, even with Microsoft webview2 installed

**Comment by zakpatterson** [comment]
Yes, it was working for me with `npm run desktop`, but not after `npm run desktop-release`, and trying the resulting binary...

**Comment by thegrims** [comment]
Weirdly, getting the defualt create-react-app page when running `npm run desktop`
image

**Comment by thegrims** [comment]
@zakpatterson I think the icon path needs to be fixed
` thread 'main' panicked at 'error found during tauri-build: `../../.icons/icon.ico` not found; required for generating a Windows Resource file during tauri-build', src/build.rs:8:5 `

**Comment by thegrims** [comment]
@zakpatterson  thread 'main' panicked at 'error found during tauri-build: `../../../public/favicon.ico` not found; required for generating a Windows Resource file during tauri-build', src/build.rs:8:5

**Comment by thegrims** [comment]
We'll get there eventually lol

**Comment by zakpatterson** [comment]
Yea, I'm seeing it working well in dev mode (`npm run desktop`), but the exe is just a blank screen with no console output and I don't know how to debug it yet...

**Comment by zakpatterson** [comment]
https://github.com/ustaxes/UsTaxes/pull/297/files#diff-178eb260a4684a522b143b09d014787ddb8ca22a72b5ea55676d54111af15367R6

This part should just be less one `../`, give it a try?

**Comment by thegrims** [comment]
No dice, unfortunately. I have had trouble referencing icon files in the public folder in the Tauri build in the past as well.  ¯\_(ツ)_/¯

**Comment by zakpatterson** [comment]
I had to add a setting to allow importing of our compiled js, per this [tauri issue](https://github.com/tauri-apps/tauri/issues/1793).

**Comment by thegrims** [comment]
Working perfectly now for both the build and the preview

**Comment by thegrims** [comment]
It would be a nice improvement to have a default file name and extension for desktop pdf printing 
image

**Review by thegrims — APPROVED** [review]
LGTM

**Comment by zakpatterson** [comment]
Great, agreed about the default save location, and default file name applies for the browser version too, will make an issue.

**Pull request merged**
